checking session status: use hasattr
If sessions doesn't exist, python raises an exception:
AttributeError: GoodreadsClient instance has no attribute 'session'